### PR TITLE
Implement support for auth configuration file

### PR DESCRIPTION
**Pull request by WillAyd**
Other servers like CMangos provide separate configuration files for auth, world, etc...we may ultimately want to create different sections in one toml file and let serde do the parsing for us. But hope this simple solution works as a starting point

### CODE REVIEW

**Comment by WillAyd** [comment]
Noted from other conversation about goals for this project - don't think config parsing is on the radar. Let's close for now - can serve as a reference for others in the future

**Comment by gtker** [comment]
Thanks for the PR, although I'll sadly have to decline.

As I wrote in the other issue #2 I'm not really interested in making this a usable server per se, more just using it for prototyping and showcasing how the client works.

This may change later but right now I want it to be as simple as possible so that others who might not be familiar with Rust can use it to create their own servers.

If you want to work on a server that's intended to be "fully featured", then [`wrath-rs`](https://github.com/Victov/wrath-rs) is a good one. 

If you want to work with Vanilla then you could try getting pathfinding to work on `wow_vanilla_server` using [`namigator-rs`](https://github.com/gtker/namigator-rs). I haven't really looked into it so I'm not entirely show how it even works. All I currently have is [this short snippet](https://github.com/gtker/wow_vanilla_server/blob/645455c6a6e92fb11bc4b93c999e504dd52bafd0/src/world/world_handler.rs#L708) that moves the ghoul found in the human start zone arbitrarily.

Otherwise, if you're looking for something a bit simpler, I would mind if [the GM command parsing](https://github.com/gtker/wow_vanilla_server/blob/645455c6a6e92fb11bc4b93c999e504dd52bafd0/src/world/world_handler.rs#L342) was split into separate text parsing and execution. So for example parsing an enum from the strings which is then actually used for executing the command.

**Comment by WillAyd** [comment]
OK cool thanks for the resources. Not personally familiar with wrath but the latter two seem interesting. If I figure out something useful can push up PRs on those

**Comment by gtker** [comment]
I have also sent you a message on the [awesome-wow-rust](https://github.com/arlyon/awesome-wow-rust) discord regarding some other projects.

**Pull request closed without merging**
